# Should be first line.
command: python train_mlp.py -D configs/data/m1.yml -M configs/models/mlp.yml -E configs/evaluation/flow_marginals.yml

seed: 42
model:
  lr: 0.0001

loader:
  batch_size: 4

trainer:
  min_epochs: 128
