# Should be first line.
command: python train_flow.py -D configs/data/m1.yml -F configs/flows/spline_autoregressive.yml -M configs/models/hierarchical_flow.yml -E configs/evaluation/flow_marginals.yml

seed: 42
model:
  lr: 0.05

loader:
  batch_size: 4

trainer:
  min_epochs: 1
