# Should be first line.
command: python train_marginal_flow.py -D configs/data/m1m2.yml -F configs/flows/planar.yml -M configs/models/hierarchical_marginal_flow.yml -E configs/evaluation/flow_marginals.yml configs/evaluation/flow_heatmap_2d.yml

seed: 42
model:
  lr: 0.01

loader:
  batch_size: 4

flow:
  input_dim: 1

trainer:
  earlystopping:
    patience: 1
