# Should be first line.
command: python train_flow_sb.py -D configs/data/m1m2_sb.yml -F configs/flows/planar.yml -M configs/models/hierarchical_flow_sb.yml -E configs/evaluation/flow_heatmap_m1m2z.yml
seed: 42
model:
  lr: 0.001
  sb_weight: 0
  object: models.normalizing_flow.HierarchicalNormalizingBayesianFlowSB

loader:
  batch_size: 32

flow:
  object: models.planar.bayesian_planar
  input_dim: 2

trainer:
  earlystopping:
    patience: 1
  min_epochs: 128

dataset:
  train_val_test_split: [1.0, 0.0, 0.0]
