# Should be first line.
command: python train_flow_sb.py -D configs/data/m1m2zchi_sb.yml -F configs/flows/planar.yml -M configs/models/hierarchical_flow_sb.yml -E configs/evaluation/flow_marginals.yml -T configs/trainers/trainer_sb.yml
seed: 42
model:
  sb_weight: 0

loader:
  batch_size: 32

flow:
  num_layers: 10
  input_dim: 4

trainer:
  object: trainers.trainer.Trainer
  min_epochs: 256
  limit_train_batches: 1024
  limit_val_batches: 1024

dataset:
  train_val_test_split: [0.0, 1.0, 0.0]
