# Should be first line.
command: python train_flow.py -D configs/data/m1m2.yml -F configs/flows/realnvp.yml -M configs/models/hierarchical_flow.yml -E configs/evaluation/flow_marginals.yml configs/evaluation/flow_heatmap_2d.yml

seed: 42
model:
  lr: 0.0003

loader:
  batch_size: 4
trainer:
  min_epochs: 5
flow:
  input_dim: 2
  num_transforms: 10
  hidden_dims: [32]