# Should be first line.
command: python train_flow.py -D configs/data/m1q.yml -F configs/flows/planar.yml -M configs/models/hierarchical_flow.yml -E configs/evaluation/flow_marginals.yml configs/evaluation/flow_heatmap_2d.yml
# configs/evaluation/flow_marginals.yml

seed: 42
model:
  lr: 0.01

loader:
  batch_size: 128

flow:
  input_dim: 2

trainer:
  earlystopping:
    patience: 1

dataset:
  train_val_test_split: [1.0, 0.0, 0.0]